version: '3'
networks:
  web:
    external: true
  treasurehunt-backend:

services:
  proxy:
    image: nginx:1.25-alpine
    depends_on:
    - webhook
    networks:
    - web
    - treasurehunt-backend
    volumes:
    - ./proxy/server.conf:/etc/nginx/conf.d/default.conf:ro
    expose:
    - 80
    logging:
      driver: "none"
    restart: unless-stopped

  webhook:
    build: ./webhook
    depends_on:
    - db
    networks:
    - treasurehunt-backend
    volumes:
    - ./data:/data:rw
    - ./wom-source.pem:/keys/wom-source.pem:ro
    env_file:
    - config.env
    expose:
    - 9000
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped

  db:
    image: mysql:5.7.43
    networks:
    - treasurehunt-backend
    env_file: config.env
    logging:
      driver: "none"
    restart: unless-stopped

  db-client:
    build: ./mysql-client
    depends_on:
    - db
    networks:
    - treasurehunt-backend
    env_file: config.env
    logging:
      driver: "none"

  database-manager:
    image: phpmyadmin:5.2.1-apache
    depends_on:
    - db
    networks:
    - web
    - treasurehunt-backend
    env_file: config.env
    environment:
    - "PMA_HOST=db"
    expose:
    - "80"
    stdin_open: true
    tty: true
    logging:
      driver: "none"
