# Base docker-compose.yml file for the Treasure Hunt backend services

services:
  proxy:
    image: nginx:1.25-alpine
    depends_on:
    - webhook
    volumes:
    - ./proxy/server.conf:/etc/nginx/conf.d/default.conf:ro
    - ./webhook/src:/var/www/html:ro
    expose:
    - 80
    logging:
      driver: "none"
    restart: unless-stopped

  webhook:
    build: ./webhook
    depends_on:
    - db
    volumes:
    - ./data:/data:rw
    - ./wom-source.pem:/keys/wom-source.pem:ro
    env_file:
    - config.env
    expose:
    - 9000
    logging:
      driver: "local"
      options:
        max-size: "10m"
    restart: unless-stopped

  db:
    image: mysql:5.7.43
    env_file: config.env
    logging:
      driver: "none"
    restart: unless-stopped
