# Custom docker-compose.yml file for deployment

networks:
  web:
    external: true
  treasurehunt-backend:

volumes:
  treasurehuntbot-db:
    external: true

services:
  proxy:
    networks:
    - web
    - treasurehunt-backend
    restart: unless-stopped
    labels:
    - "traefik.enable=true"
    - "traefik.docker.network=web"
    - "traefik.http.routers.treasurehuntbot-proxy.rule=Host(`treasurehuntbot.digit.srl`)"
    - "traefik.http.routers.treasurehuntbot-proxy.priority=1"
    - "traefik.http.routers.treasurehuntbot-proxy.entrypoints=websecure"

  webhook:
    networks:
    - treasurehunt-backend
    restart: unless-stopped

  db:
    networks:
    - treasurehunt-backend
    volumes:
    - treasurehuntbot-db:/var/lib/mysql:rw
    restart: unless-stopped
    command:
    - --innodb-buffer-pool-size=256M
    - --innodb-log-file-size=64M
    - --innodb-flush-method=O_DIRECT
    - --max-connections=50
    - --performance-schema=OFF
    - --table-definition-cache=200
    - --table-open-cache=200
    - --innodb-buffer-pool-instances=1
    - --innodb-flush-log-at-trx-commit=2
    mem_limit: 512m
    mem_reservation: 256m
    memswap_limit: 512m
    mem_swappiness: 0
    oom_kill_disable: false

  db-client:
    build: ./mysql-client
    depends_on:
    - db
    networks:
    - treasurehunt-backend
    env_file: config.env
    logging:
      driver: "none"

  database-manager:
    image: phpmyadmin:5.2.3-apache
    depends_on:
    - db
    networks:
    - web
    - treasurehunt-backend
    env_file: config.env
    environment:
    - "PMA_HOST=db"
    - "PMA_ABSOLUTE_URI=https://treasurehuntbot.digit.srl/phpmyadmin/"
    expose:
    - "80"
    stdin_open: true
    tty: true
    logging:
      driver: "none"
    labels:
    - "traefik.enable=true"
    - "traefik.docker.network=web"
    - "traefik.http.routers.treasurehuntbot-admin-secure.rule=Host(`treasurehuntbot.digit.srl`) && PathPrefix(`/phpmyadmin`)"
    - "traefik.http.routers.treasurehuntbot-admin-secure.priority=100"
    - "traefik.http.routers.treasurehuntbot-admin-secure.entrypoints=websecure"
    - "traefik.http.routers.treasurehuntbot-admin-secure.middlewares=treasurehuntbot-admin-stripprefix"
    - "traefik.http.routers.treasurehuntbot-admin-insecure.rule=Host(`treasurehuntbot.digit.srl`) && PathPrefix(`/phpmyadmin`)"
    - "traefik.http.routers.treasurehuntbot-admin-insecure.priority=100"
    - "traefik.http.routers.treasurehuntbot-admin-insecure.entrypoints=web"
    - "traefik.http.routers.treasurehuntbot-admin-insecure.middlewares=treasurehuntbot-admin-redirecthttps,treasurehuntbot-admin-stripprefix"
    - "traefik.http.middlewares.treasurehuntbot-admin-redirecthttps.redirectscheme.scheme=https"
    - "traefik.http.middlewares.treasurehuntbot-admin-redirecthttps.redirectscheme.permanent=true"
    - "traefik.http.middlewares.treasurehuntbot-admin-stripprefix.stripprefix.prefixes=/phpmyadmin"
