# Custom docker compose file for development

volumes:
  db-data:

services:
  proxy:
    volumes:
      - ./proxy/server.conf:/etc/nginx/conf.d/default.conf:ro
      - ./webhook/src:/var/www/html:ro
    ports:
      - 8888:80
    logging:
      driver: "none"
    restart: unless-stopped

  webhook:
    build:
      context: ./webhook
      dockerfile: Dockerfile.dev
    volumes:
      - ./webhook/src:/var/www/html:rw
      - ./webhook/html2pdf:/html2pdf:rw
      - ./data:/data:rw
      - ./wom-source.pem:/keys/wom-source.pem:ro

  db:
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306 # Expose DB locally

  database-manager:
    image: phpmyadmin:5.2.3-apache
    depends_on:
    - db
    env_file: config.env
    ports:
      - 8889:80
    environment:
    - "PMA_HOST=db"
    logging:
      driver: "none"
